### ISSUE TITLE
Setup Tailwind in Project

### ISSUE THREAD

**Issue by DaemonLoki** [oseven-development/petrakip-app#31]
Tailwind aufsetzen mit einigen Defaults als Farben, etc.

Dazu ordentliches Setup von PostCSS.

**Comment by maxhaensel** [comment]
Do we need Tailwind, IONIC comes with styling?

**Comment by philschmid** [comment]
I am strictly against adding Tailwindcss or any alternative styling. Ionic offers a wide variety of components https://ionicframework.com/docs/components, which are optimized and test for Android and IOS for all the devices for dark-mode light-mode etc. 
Adding an additional library for that increases complexity and the effort to maintain. 

For me having a slight difference between the sketches and the implementation are okay.
